name: flutter_external
description: Identity Service â€” External Client Example (Flutter)
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  pointycastle: ^3.9.1
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
